/*=================================================口袋钱包重构=======================================================*/
//数据字典明细-根据dicCode查询
//启用方式
const ENABLE_STATUS = "ENABLE_STATUS";
//认证模型
const AUTH_MODEL = "AUTH_MODEL";
//业务类型
const BUSINESS_TYPE = "BUSINESS_TYPE";
//认证模型类型
const AUTH_MODEL_TYPE = "AUTH_MODEL_TYPE";
//信用卡代偿
const CREDIT_CARD_COMPENSATION = "CREDIT_CARD_COMPENSATION";

// 活动管理
// 活动类型
const ACTIVITY_TYPE_MAP = {
  PROMOTION: "策略促销",
  LUCKY_DRAW: "抽奖活动",
  COUPON: "卡券礼包"
};
// 活动状态
const ACTIVITY_STATUS_MAP = {
  NOT_STARTED: "未开始",
  ON_GOING: "进行中",
  HAS_ENDED: "已结束",
  CLOSED: "已关闭"
};
// 商户渠道
const ACTIVITY_SOURCE_MAP = {
  SHOP: "商户",
  CHANNEL: "渠道"
};
// 促销类
const PROMOTION_TYPE_MAP = {
  PROMOTION_INTEREST_FREE: "借款免息",
  PROMOTION_DISCOUNT: "利息折扣"
};
// 使用场景
const USE_CASE_MAP = {
  CONSUMER: "消费贷",
  CASH: "预借现金",
  CREDIT_CARD_COMPENSATION: "信用卡待还"
};
// 卡券状态
const COUPON_STATUS_MAP = {
  INEFFECTIVE: "未生效",
  PUBLISHED: "已生效",
  RECEIVED: "已领完",
  EXPIRED: "已过期 ",
  CANCELED: "取消发行",
  DISCARDED: "已下架"
};
// 卡券类型
const COUPON_TYPE_MAP = {
  INTEREST_FREE: "免息券",
  DISCOUNT: "折扣券"
};

//借款申请状态(还款状态)
const LOAN_STATUS = "LOAN_STATUS";

//逾期状态
const OVERDUE_STATUS = "OVERDUE_STATUS";

//当前审核节点(审核状态)
const REVIEW_STATUS = "REVIEW_STATUS";

//巡检状态
const ROUTING_STATUS = "ROUTING_STATUS";
//巡检状态-额度巡检记录里面的枚举
const CHECK_STATUS = "CHECK_STATUS";

//巡检结果
const ROUTING_RESULT = "ROUTING_RESULT";
//巡检结果-额度巡检记录管理里面的枚举
const CHECK_RESULT = "CHECK_RESULT";

//账户性质
const ACCOUNT_CHARACTER = "ACCOUNT_CHARACTER";

//资产状态
const ASSET_STATUS = "ASSET_STATUS";

//推送状态
const PUSH_STATUS = "PUSH_STATUS";

//放款模式
const LOAN_MODEL = "LOAN_MODEL";

//经营状况
const MANAGE_STATUS = "MANAGE_STATUS";

//申请表数据类型
const APPLICATION_FORM_TYPE = "APPLICATION_FORM_TYPE";

//学历
const EDUCATION_BACKGROUND = "EDUCATION_BACKGROUND";

//亲属关系
const RELATIONSHIP = "RELATIONSHIP";

//其它关系
const OTHERSHIP = "OTHERSHIP";

//申请状态
const APPLICATION_STATUS = "APPLICATION_STATUS";

//婚姻状态
const MARITAL_STATUS = "MARITAL_STATUS";

//所属行业
const WORK_TYPE = "WORK_TYPE";

//单位性质
const WORK_ORG_NATURE = "WORK_ORG_NATURE";

//借款人资金运转状况
const FUND_USE_STATUS = "FUND_USE_STATUS";

//财务状况
const FINANCE_STATUS = "FINANCE_STATUS";

//调账类型
const ADJUSTMENT_TYPE = "ADJUSTMENT_TYPE";

//划账代办审核状态
const ADJUSTMENT_AUDIT_STATUS = "ADJUSTMENT_AUDIT_STATUS";

//财务管理-调账详情-操作类型
const ADJUSTMENT_OPERATE_TYPE = "ADJUSTMENT_OPERATE_TYPE";

//财务管理-调账详情-操作状态
const ADJUSTMENT_OPERATE_STATUS = "ADJUSTMENT_OPERATE_STATUS";

//出账状态
const BILL_STATUS = "BILL_STATUS";

//账户性质
const ACCOUNT_NATURE = 'ACCOUNT_NATURE';

//是否已分期
const DIVIDE_STATUS = "DIVIDE_STATUS";

//贷款管理 逾期记录
const OVERDUE_FLAG = "OVERDUE_FLAG";

//信用卡月账单还款状态枚举
const CREDIT_REPAY_STATUS = "CREDIT_REPAY_STATUS";

//信用卡月账单逾期状态枚举
const CREDIT_OVERDUE_STATUS = "CREDIT_OVERDUE_STATUS";

//信用卡交易明细类型枚举
const CREDIT_TRADE_DETAIL_TYPE = "CREDIT_TRADE_DETAIL_TYPE";

//账单类型
const LOAN_TYPE = "LOAN_TYPE";

//还款状态
const LOAN_APPLY_REPAY_STATUS = "LOAN_APPLY_REPAY_STATUS";

//还款情况
const REPAY_SITUATION = "REPAY_SITUATION";

//性别
const SEX = "SEX";

//放款状态
const GRANT_STATUS = "GRANT_STATUS";

//还款方式
const REPAYMENT_MODEL = "REPAYMENT_MODEL";

//终止状态
const LOAN_CANCEL_STATUS = "LOAN_CANCEL_STATUS";

//还款管理里面的还款状态
const LOAN_BILL_REPAY_STATUS = "LOAN_BILL_REPAY_STATUS";
//授信类型
const CREDIT_TYPE = "CREDIT_TYPE";

//提现状态
const ADJUSTMENT_FUNDS_OPERATE_STATUS = "ADJUSTMENT_FUNDS_OPERATE_STATUS";
//事件记录类型
const EVENRECORD_TYPE = "EVENRECORD_TYPE";

//风控-申请类型枚举
const APPLICATION_TYPE = "APPLICATION_TYPE";

//风控-审核记录中审核结果枚举
const AUDIT_RESULT_TYPE = "AUDIT_RESULT_TYPE";

//风控-电核记录中的联系人关系
const CONTACT_RELATIONSHIP = "CONTACT_RELATIONSHIP";

//风控-电核记录中的电核状态
const ELECTRIC_STATE = "ELECTRIC_STATE";

//风控-电核记录-联系人类型
const CONTACT_TYPE = "CONTACT_TYPE";

//风控-是否知悉贷款
const KNOWLEDGE_TYPE = "KNOWLEDGE_TYPE";

//风控-用户额度管理-是否有效
const USER_PROPERTY_BIND_TYPE = "USER_PROPERTY_BIND_TYPE";

//商户管理 - 订单管理 - 订单类型
const ORDER_TYPE = "ORDER_TYPE";

//商户管理 - 订单管理 - 交易状态
const DEAL_STATUS = "DEAL_STATUS";

//商户管理 - 商户结算 - 结算方式
const CLEAR_WAY = "CLEAR_WAY";

//商户管理 - 商户结算 - 结算状态
const CLEAR_STATUS = "CLEAR_STATUS";

//商户管理 - 商户结算 - 放款账户
const LOAN_BANK_ACCOUNT = "LOAN_BANK_ACCOUNT";

//商户管理 - 退款退货 - 退货状态
const RETURN_GOODS_STATUS = "RETURN_GOODS_STATUS";

//支付通道
const PAY_CHANNEL = 'PAY_CHANNEL';

//账户
const ADJUST_ACCOUNT_TYPE = 'ADJUST_ACCOUNT_TYPE';

export default {
  ENABLE_STATUS,
  AUTH_MODEL,
  BUSINESS_TYPE,
  AUTH_MODEL_TYPE,
  CREDIT_CARD_COMPENSATION,
  ACTIVITY_TYPE_MAP,
  ACTIVITY_STATUS_MAP,
  ACTIVITY_SOURCE_MAP,
  PROMOTION_TYPE_MAP,
  USE_CASE_MAP,
  COUPON_STATUS_MAP,
  COUPON_TYPE_MAP,
  LOAN_STATUS,
  REVIEW_STATUS,
  ROUTING_STATUS,
  ROUTING_RESULT,
  ACCOUNT_CHARACTER,
  ASSET_STATUS,
  PUSH_STATUS,
  LOAN_MODEL,
  MANAGE_STATUS,
  APPLICATION_FORM_TYPE,
  EDUCATION_BACKGROUND,
  RELATIONSHIP,
  OTHERSHIP,
  APPLICATION_STATUS,
  MARITAL_STATUS,
  WORK_TYPE,
  WORK_ORG_NATURE,
  FUND_USE_STATUS,
  FINANCE_STATUS,
  ADJUSTMENT_TYPE,
  ADJUSTMENT_OPERATE_TYPE,
  ADJUSTMENT_OPERATE_STATUS,
  OVERDUE_STATUS,
  BILL_STATUS,
  DIVIDE_STATUS,
  CREDIT_OVERDUE_STATUS,
  CREDIT_TRADE_DETAIL_TYPE,
  LOAN_TYPE,
  CREDIT_REPAY_STATUS,
  SEX,
  GRANT_STATUS,
  REPAYMENT_MODEL,
  LOAN_CANCEL_STATUS,
  LOAN_APPLY_REPAY_STATUS,
  REPAY_SITUATION,
  LOAN_BILL_REPAY_STATUS,
  CREDIT_TYPE,
  ADJUSTMENT_FUNDS_OPERATE_STATUS,
  APPLICATION_TYPE,
  EVENRECORD_TYPE,
  ADJUSTMENT_AUDIT_STATUS,
  AUDIT_RESULT_TYPE,
  CONTACT_RELATIONSHIP,
  ELECTRIC_STATE,
  CONTACT_TYPE,
  KNOWLEDGE_TYPE,
  USER_PROPERTY_BIND_TYPE,
  ORDER_TYPE,
  DEAL_STATUS,
  CLEAR_WAY,
  CLEAR_STATUS,
  LOAN_BANK_ACCOUNT,
  RETURN_GOODS_STATUS,
  OVERDUE_FLAG,
  ACCOUNT_NATURE,
  CHECK_STATUS,
  CHECK_RESULT,
  PAY_CHANNEL,
  ADJUST_ACCOUNT_TYPE
};
